import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ToDoContainer from '../components/ToDoContainer'

const Home: NextPage = () => {
  return (
    <div style={{
      background: 'linear-gradient(#e66465, #9198e5)',
      height: '100vh',
      display: 'flex',
      justifyContent: 'center',
    }}>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <ToDoContainer />
    </div>
  )
}

export default Home
